<?php

namespace Tests\Feature;

use App\Models\PaymentMethod;
use App\Models\Project;
use App\Models\ProjectStep;
use App\Models\Transaction;
use App\Models\TransactionCategory;
use App\Models\User;

it('allows authenticated users to do transaction crud with autogenerated code and verified_at', function () {
    $user = User::factory()->create();

    $project = Project::factory()->create(['code' => 'ABC']);
    $step = ProjectStep::factory()->create([
        'code' => 'S01',
        'project_id' => $project->id,
    ]);
    $category = TransactionCategory::factory()->create();
    $payment = PaymentMethod::factory()->create();

    $this->actingAs($user)
        ->get('/transactions')
        ->assertOk();

    // create and make sure code/verified_at are not taken from input
    // also submit 'none' for optional relationship selects
    $response = $this->actingAs($user)
        ->post('/transactions', [
            'project_id' => $project->id,
            'project_step_id' => $step->id,
            'category_id' => $category->id,
            'payment_method_id' => $payment->id,
            'date' => '2026-02-26',
            'amount' => 100,
            'type' => 'income',
            'description' => 'First tx',
            'partner_id' => 'none',
            'contractor_id' => 'none',
            'vendor_id' => 'none',
            'code' => 'SHOULD-BE-IGNORED',
            'verified_at' => '2000-01-01',
        ]);

    $response->assertRedirect('/transactions');

    $tx = Transaction::latest('id')->first();
    expect($tx)->not->toBeNull();
    expect($tx->code)->toBe('ABC-S01-1');
    expect($tx->verified_at->format('Y-m-d'))->toBe(now()->format('Y-m-d'));

    // update without changing project/step should keep same code and still override verified_at
    // update again sending "none" for optional fields to ensure normalization
    $response = $this->actingAs($user)
        ->put("/transactions/{$tx->id}", [
            'project_id' => $project->id,
            'project_step_id' => $step->id,
            'category_id' => $category->id,
            'payment_method_id' => $payment->id,
            'date' => '2026-02-27',
            'amount' => 150,
            'type' => 'income',
            'description' => 'Updated tx',
            'partner_id' => 'none',
            'contractor_id' => 'none',
            'vendor_id' => 'none',
            'code' => 'ANOTHER-IGNORED',
            'verified_at' => '1999-01-01',
        ]);

    $response->assertRedirect('/transactions');
    $tx->refresh();
    expect($tx->code)->toBe('ABC-S01-1');
    expect($tx->verified_at->format('Y-m-d'))->toBe(now()->format('Y-m-d'));
    expect($tx->partner_id)->toBeNull();
    expect($tx->contractor_id)->toBeNull();
    expect($tx->vendor_id)->toBeNull();

    // change project/step to force regeneration
    $project2 = Project::factory()->create(['code' => 'DEF']);
    $step2 = ProjectStep::factory()->create([
        'code' => 'S02',
        'project_id' => $project2->id,
    ]);

    $response = $this->actingAs($user)
        ->put("/transactions/{$tx->id}", [
            'project_id' => $project2->id,
            'project_step_id' => $step2->id,
            'category_id' => $category->id,
            'payment_method_id' => $payment->id,
            'date' => '2026-03-01',
            'amount' => 200,
            'type' => 'expense',
            'description' => 'Moved tx',
        ]);

    $response->assertRedirect('/transactions');
    $tx->refresh();
    expect($tx->code)->toBe('DEF-S02-1');

    // delete
    $this->actingAs($user)
        ->delete("/transactions/{$tx->id}")
        ->assertRedirect('/transactions');

    $this->assertDatabaseMissing('transactions', ['id' => $tx->id]);
});
